### ISSUE TITLE
Validate org settings: force github enterprise plan

### ISSUE THREAD

**Issue by heurtematte** [EclipseFdn/otterdog-defaults#10]
Is it possible to check and force github plan to enterprise (field `plan`) not free, for newly org created by default? 

In this file: https://github.com/EclipseFdn/otterdog-defaults/blob/main/validate-org-settings.py

**Comment by netomi** [comment]
we could do that, however, not enforcing it gives you freedom to also include orgs that should not be part of the enterprise.

We have at least one case like that for now, but here we use a different default config anyways. So yeah we could change it.
