### ISSUE TITLE
codecov upload token

### ISSUE THREAD

**Issue by elBoberido** [EclipseFdn/otterdog-defaults#8]
It seems codecov now requires an uplaod token. I'm not able to check whether there is one set up for the iceoryx repos. Can you check whether there is one and add one if not.

https://docs.codecov.com/docs/adding-the-codecov-token#github-actions
https://docs.codecov.com/docs/frequently-asked-questions#section-where-is-the-repository-upload-token-found

**Comment by elBoberido** [comment]
@netomi pinging you since you created the other issues on this repo

**Comment by netomi** [comment]
You can check the current configuration at https://otterdog.eclipse.org/projects/technology.iceoryx

This is the wrong place to discuss such things, to raise an issue to add such a token either create one at https://github.com/eclipse-iceoryx/.eclipsefdn or at the EF HelpDesk.

**Comment by netomi** [comment]
To my knowledge we have setup something like this for at least one repo: https://otterdog.eclipse.org/projects/adoptium/repos/adoptium.net-redesign#secrets

**Comment by netomi** [comment]
so ideally you can create a PR to the .eclipsefdn repo of iceoryx with the requested secret for the repo you wanna have it setup, then share the token with us as explained here: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/wikis/Sharing-secrets

**Comment by netomi** [comment]
you can copy the configuration from adoptium:

```
      secrets: [
        orgs.newRepoSecret('CODECOV_TOKEN') {
          value: "TBD",
        },
      ],
```

the value can be omitted, will be filled in by us after receiving the secret from you.
